### PR TITLE
DEV: Use the new modal api

### PR DESCRIPTION
**Pull request by CvX**

### CODE REVIEW

**Review by jjaffeux — APPROVED** [review]

**Comment by chapoi** [comment]
There is a wrapping class/element that shouldn't be there
image

**Comment by CvX** [comment]
@chapoi that's part of the current modal implementation in core: https://github.com/discourse/discourse/blame/main/app/assets/javascripts/discourse/app/components/modal-container.hbs#L1-L1

**Comment by chapoi** [comment]
But the other new d-modals dont have that I think?

**Comment by CvX** [comment]
I think they do? (it's there for keyboard shortcuts modal and report/flag post modal for example)

**Comment by chapoi** [comment]
Lol youre completely right, ignore me

**Pull request merged**
